---
- name: Initial Upgrade, Restart If Required And Show Uptime
  hosts: all
  remote_user: "{{ remote_username }}"
  become: yes

  tasks:
  - name: Update Cache And Upgrade
    ansible.builtin.apt:
      update_cache: yes
      upgrade: dist
      autoremove: yes
  
  - name: Check If Reboot Required
    ansible.builtin.stat:
      path: /var/run/reboot-required
    register: reboot_required_file
  
  - name: Reboot If Required
    ansible.builtin.reboot:
      msg: "Reboot Initiated By Ansible"
      test_command: uptime
    when: reboot_required_file.stat.exists
  
  - name: Run Uptime
    ansible.builtin.command: uptime -p
    register: out
  
  - name: Show Uptime Output
    ansible.builtin.debug:
      var: out.stdout_lines
