---
- name: Create Ansible User With Key Based Authentication
  hosts: all
  remote_user: root

  tasks:
    - name: Create Ansible User
      ansible.builtin.user:
        name: "{{ remote_username }}"
        password: "{{ remote_password | password_hash('sha512') }}"
        shell: /bin/bash
        groups: sudo
        append: yes

    - name: Set Authorized Key From File
      ansible.posix.authorized_key:
        user: "{{ remote_username }}"
        state: present
        key: "{{ lookup('file', host_ssh_key_path) }}"

    - name: Create Sudoers File (Without Password)
      ansible.builtin.copy:
        content: "{{ remote_username }}	ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/{{ remote_username }}
        owner: root
        group: root
        mode: '0440'